name: moodly_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_bloc: ^9.1.1
  http_parser: ^4.0.2
  http: ^1.3.0
  image_picker: ^0.8.7+4
  intl: ^0.20.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/icons/moodly_icon.svg
   - assets/icons/moodly_icon_outlined.svg
   - assets/icons/icon_add.svg
   - assets/icons/icon_add_outlined.svg
   - assets/icons/icon_all_entries.svg
   - assets/icons/icon_all_entries_outlined.svg
   - assets/icons/icon_fasties_settings.svg
   - assets/icons/icon_home.svg
   - assets/icons/icon_home_outlined.svg
   - assets/icons/icon_info.svg
   - assets/icons/icon_mood_angry.svg
   - assets/icons/icon_mood_anxious.svg
   - assets/icons/icon_mood_good.svg
   - assets/icons/icon_mood_happy.svg
   - assets/icons/icon_mood_loving.svg
   - assets/icons/icon_mood_moody.svg
   - assets/icons/icon_mood_sad.svg
   - assets/icons/icon_mood_tired.svg
   - assets/icons/icon_settings.svg
   - assets/icons/icon_settings_outlined.svg
   - assets/images/moodly_speech.png
   - assets/data/categories.json
   - assets/data/days.json
   - assets/data/fasties.json
   - assets/data/journalEntries.json
   - assets/data/moods.json


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf  